from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import openpyxl
import pandas as pd


def _iter_data_files(data_dir: Path) -> Iterable[Path]:
    patterns = ("*.csv", "*.xlsx", "*.xlsm", "*.xls")
    files: list[Path] = []
    for pattern in patterns:
        files.extend(data_dir.rglob(pattern))
    return sorted(path for path in files if path.is_file())


def _csv_section(path: Path, repo_root: Path) -> str:
    frame = pd.read_csv(path)
    relative = path.relative_to(repo_root)
    columns = ", ".join(frame.columns.astype(str).tolist())
    return "\n".join(
        [
            f"## {relative}",
            "",
            "- Format: CSV",
            f"- Rows: {len(frame):,}",
            f"- Columns: {len(frame.columns)}",
            f"- Column names: {columns}",
            "",
        ]
    )


def _excel_section(path: Path, repo_root: Path) -> str:
    workbook = openpyxl.load_workbook(path, read_only=True, data_only=True)
    relative = path.relative_to(repo_root)

    sheet_names = workbook.sheetnames
    active_sheet = workbook[sheet_names[0]]
    row_iter = active_sheet.iter_rows(min_row=1, max_row=1, values_only=True)
    header_row = next(row_iter, ())
    columns = [str(value) for value in header_row if value is not None]

    return "\n".join(
        [
            f"## {relative}",
            "",
            "- Format: Excel workbook",
            f"- Sheets: {', '.join(sheet_names)}",
            f"- Active sheet audited: {active_sheet.title}",
            f"- Rows: {max(active_sheet.max_row - 1, 0):,}",
            f"- Columns: {len(columns)}",
            f"- Column names: {', '.join(columns)}",
            "",
        ]
    )


def build_inventory_document(repo_root: Path, data_dir: Path) -> str:
    sections = [
        "# Data Inventory Audit",
        "",
        "This document is generated by `src/data_inventory_audit.py` and summarizes every CSV and Excel file currently present under `data/`.",
        "",
    ]

    for path in _iter_data_files(data_dir):
        suffix = path.suffix.lower()
        if suffix == ".csv":
            sections.append(_csv_section(path, repo_root))
        elif suffix in {".xlsx", ".xlsm", ".xls"}:
            sections.append(_excel_section(path, repo_root))

    return "\n".join(sections).strip() + "\n"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a markdown inventory of data files.")
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument("--data-dir", type=Path, default=Path("data"))
    parser.add_argument("--output", type=Path, default=Path("docs/data_inventory.md"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    content = build_inventory_document(args.repo_root, args.data_dir)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote data inventory to {args.output}")


if __name__ == "__main__":
    main()
